name: Docs

on: [push]

jobs:
  build_doc:

    runs-on: ubuntu-latest

    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
    - uses: actions/checkout@v2
    - name: Activate license
      uses: MirageNet/unity-runner@3.1.0
      with:
        entrypoint: /activate.sh
    - name: Generate Solution
      uses: MirageNet/unity-runner@3.1.0
      with:
        # Arguments to pass to unity
        args: -buildTarget StandaloneWindows64 -customBuildName Mirage -customBuildPath ./build/StandaloneWindows64 -projectPath . -executeMethod  UnityEditor.SyncVS.SyncSolution -quit
    - name: DebugPath
      run: ls -l
    - name: Generate API
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: metadata --logLevel Warning --warningsAsErrors doc/docfx.json
    - name: Compile Docs
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: build --logLevel Warning --warningsAsErrors doc/docfx.json
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      if: github.ref == 'refs/heads/master'
      with:
        # Create incremental commit instead of doing push force
        keep_history: true
        # Allow an empty commit to be created
        allow_empty_commit: true
        jekyll: false
        # Build directory to deploy
        build_dir: doc/_site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
